name: dofia_the_book
description: A book discovery and reading app

# Prevents accidental publishing to pub.dev
publish_to: "none"

# The version number for your application. Increment this for new releases.
# The build number (after the '+') is often incremented for each build.
version: 1.0.0+1

environment:
  # Specifies the Dart SDK range this project is compatible with.
  # Keeps you on Dart 3.x, which is current stable.
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  # Core Flutter framework.
  flutter:
    sdk: flutter
  carousel_slider: ^5.1.1

  # For iOS-style icons. Updated to the latest stable version.
  cupertino_icons: ^1.0.8 # Updated from 1.0.2
  provider: ^6.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  # For writing Flutter unit and widget tests.
  flutter_test:
    sdk: flutter

  # Recommended set of linting rules for Flutter projects.
  # Updated to the latest recommended version for Flutter 3 / Dart 3.
  flutter_lints: ^6.0.0 # Updated from ^6.0.0 - this is a critical update for modern Flutter

flutter:
  # Enables Material Design styling for your app.
  uses-material-design: true

  # To add assets to your application, add an assets section below.
  assets:
    - assets/share/logoDofia.png
    - assets/images/
    - assets/images/book_covers/
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section below.
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
